// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// ==============================================================
#ifndef XLINEARB_H
#define XLINEARB_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xlinearb_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_BaseAddress;
} XLinearb_Config;
#endif

typedef struct {
    u64 Ctrl_BaseAddress;
    u32 IsReady;
} XLinearb;

typedef u32 word_type;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XLinearb_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XLinearb_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XLinearb_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XLinearb_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XLinearb_Initialize(XLinearb *InstancePtr, u16 DeviceId);
XLinearb_Config* XLinearb_LookupConfig(u16 DeviceId);
int XLinearb_CfgInitialize(XLinearb *InstancePtr, XLinearb_Config *ConfigPtr);
#else
int XLinearb_Initialize(XLinearb *InstancePtr, const char* InstanceName);
int XLinearb_Release(XLinearb *InstancePtr);
#endif


void XLinearb_Set_confFilterDstIPsA_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsA_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsA_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsA_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsA_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstIPsB_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstIPsB_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterDstPortsB_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterDstPortsB_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsA_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsA_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsA_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsA_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcIPsB_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcIPsB_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_0(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_1(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_2(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_3(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_4(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_4(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_5(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_5(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_6(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_6(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_7(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_7(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_8(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_8(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_9(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_9(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_10(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_10(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_11(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_11(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_12(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_12(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_13(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_13(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_14(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_14(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_15(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_15(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_16(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_16(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_17(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_17(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_18(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_18(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_19(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_19(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_20(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_20(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_21(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_21(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_22(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_22(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_23(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_23(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_24(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_24(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_25(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_25(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_26(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_26(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_27(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_27(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_28(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_28(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_29(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_29(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_30(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_30(XLinearb *InstancePtr);
void XLinearb_Set_confFilterSrcPortsB_31(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterSrcPortsB_31(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_0_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_0_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_0_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_0_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_1_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_1_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_1_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_1_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_2_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_2_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_2_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_2_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_3_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_3_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_3_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_3_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_4_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_4_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_4_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_4_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_5_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_5_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_5_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_5_o_vld(XLinearb *InstancePtr);
void XLinearb_Set_confFilterCsumAdj_6_i(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_confFilterCsumAdj_6_i(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_6_o(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_6_o_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_7(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_7_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_8(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_8_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_9(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_9_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_10(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_10_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_11(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_11_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_12(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_12_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_13(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_13_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_14(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_14_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_15(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_15_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_16(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_16_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_17(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_17_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_18(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_18_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_19(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_19_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_20(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_20_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_21(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_21_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_22(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_22_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_23(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_23_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_24(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_24_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_25(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_25_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_26(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_26_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_27(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_27_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_28(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_28_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_29(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_29_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_30(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_30_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_31(XLinearb *InstancePtr);
u32 XLinearb_Get_confFilterCsumAdj_31_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_0(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_0_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_1(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_1_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_2(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_2_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_3(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_0_3_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_0(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_0_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_1(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_1_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_2(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_2_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_3(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_1_3_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_0(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_0_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_1(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_1_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_2(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_2_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_3(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_2_3_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_0(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_0_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_1(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_1_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_2(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_2_vld(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_3(XLinearb *InstancePtr);
u32 XLinearb_Get_ip_3_3_vld(XLinearb *InstancePtr);
void XLinearb_Set_stats_0_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_0_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_0_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_0_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_0_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_0_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_0_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_0_3(XLinearb *InstancePtr);
void XLinearb_Set_stats_1_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_1_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_1_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_1_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_1_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_1_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_1_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_1_3(XLinearb *InstancePtr);
void XLinearb_Set_stats_2_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_2_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_2_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_2_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_2_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_2_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_2_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_2_3(XLinearb *InstancePtr);
void XLinearb_Set_stats_3_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_3_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_3_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_3_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_3_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_3_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_3_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_3_3(XLinearb *InstancePtr);
void XLinearb_Set_stats_4_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_4_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_4_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_4_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_4_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_4_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_4_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_4_3(XLinearb *InstancePtr);
void XLinearb_Set_stats_5_0(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_5_0(XLinearb *InstancePtr);
void XLinearb_Set_stats_5_1(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_5_1(XLinearb *InstancePtr);
void XLinearb_Set_stats_5_2(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_5_2(XLinearb *InstancePtr);
void XLinearb_Set_stats_5_3(XLinearb *InstancePtr, u32 Data);
u32 XLinearb_Get_stats_5_3(XLinearb *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
