// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lineArb_lineArb_Pipeline_stats_l_to_stats_loop25 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stats_5_0,
        stats_5_0_ap_vld,
        stats_5_1,
        stats_5_1_ap_vld,
        stats_5_2,
        stats_5_2_ap_vld,
        stats_5_3,
        stats_5_3_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] stats_5_0;
output   stats_5_0_ap_vld;
output  [31:0] stats_5_1;
output   stats_5_1_ap_vld;
output  [31:0] stats_5_2;
output   stats_5_2_ap_vld;
output  [31:0] stats_5_3;
output   stats_5_3_ap_vld;

reg ap_idle;
reg stats_5_0_ap_vld;
reg stats_5_1_ap_vld;
reg stats_5_2_ap_vld;
reg stats_5_3_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln496_fu_78_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] j_fu_38;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_1;
wire   [2:0] add_ln496_fu_84_p2;
wire   [2:0] j_1_load_fu_75_p1;
wire   [31:0] tmp_s_fu_94_p6;
wire   [1:0] tmp_s_fu_94_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

lineArb_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U347(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(tmp_s_fu_94_p5),
    .dout(tmp_s_fu_94_p6)
);

lineArb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln496_fu_78_p2 == 1'd0)) begin
            j_fu_38 <= add_ln496_fu_84_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_38 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln496_fu_78_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_38;
    end
end

always @ (*) begin
    if (((j_1_load_fu_75_p1 == 3'd0) & (icmp_ln496_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stats_5_0_ap_vld = 1'b1;
    end else begin
        stats_5_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((j_1_load_fu_75_p1 == 3'd1) & (icmp_ln496_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stats_5_1_ap_vld = 1'b1;
    end else begin
        stats_5_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((j_1_load_fu_75_p1 == 3'd2) & (icmp_ln496_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stats_5_2_ap_vld = 1'b1;
    end else begin
        stats_5_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(j_1_load_fu_75_p1 == 3'd0) & ~(j_1_load_fu_75_p1 == 3'd1) & ~(j_1_load_fu_75_p1 == 3'd2) & (icmp_ln496_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        stats_5_3_ap_vld = 1'b1;
    end else begin
        stats_5_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln496_fu_84_p2 = (ap_sig_allocacmp_j_1 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln496_fu_78_p2 = ((ap_sig_allocacmp_j_1 == 3'd4) ? 1'b1 : 1'b0);

assign j_1_load_fu_75_p1 = ap_sig_allocacmp_j_1;

assign stats_5_0 = tmp_s_fu_94_p6;

assign stats_5_1 = tmp_s_fu_94_p6;

assign stats_5_2 = tmp_s_fu_94_p6;

assign stats_5_3 = tmp_s_fu_94_p6;

assign tmp_s_fu_94_p5 = ap_sig_allocacmp_j_1[1:0];

endmodule //lineArb_lineArb_Pipeline_stats_l_to_stats_loop25
