//////////////////////////////////////////////////////////////////////////////
// be767e8644eee50b2645307571242b99d62eea726bb276dae1cba7a07fa60690
// Proprietary Note:
// XILINX CONFIDENTIAL
//
// Copyright 2015 Xilinx, Inc. All rights reserved.
// This file contains confidential and proprietary information of Xilinx, Inc.
// and is protected under U.S. and international copyright and other
// intellectual property laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
//
// US ExportControl: EAR 3E001
//
//
//       Owner:
//       Revision:       $Id: //Rodin/HEAD/src/products/sdnet/p4c-sdnet-opt/iprepo/encrypted/sdnet_v1_0/src/hw/top/ttcl/sdnet_wrapper.ttcl#30 $
//                       $Author: fmartin $
//                       $DateTime: 2020/06/29 08:16:49 $
//                       $Change: 2927269 $
//
//       Description: 
//
//////////////////////////////////////////////////////////////////////////////

module ipsec_bd_sdnet_0_3 #(
   parameter integer TDATA_NUM_BYTES             = 16,
   parameter integer TUSER_WIDTH                 = 1,
   parameter integer TID_WIDTH                   = 1,
   parameter integer TDEST_WIDTH                 = 1,
   parameter integer USER_META_DATA_WIDTH        = 581,
   parameter integer NUM_USER_EXTERNS            = 1,
   parameter integer USER_EXTERN_IN_WIDTH        = 16,
   parameter integer USER_EXTERN_OUT_WIDTH       = 160,
   parameter integer S_AXI_DATA_WIDTH            = 32,
   parameter integer S_AXI_ADDR_WIDTH            = 1,
   parameter integer M_AXI_HBM_DATA_WIDTH        = 256,
   parameter integer M_AXI_HBM_ADDR_WIDTH        = 33,
   parameter integer M_AXI_HBM_ID_WIDTH          = 6,
   parameter integer M_AXI_HBM_RESP_WIDTH        = 2
) (
   // clocks & resets
   input  wire                               s_axis_aclk,
   input  wire                               s_axis_aresetn,
   input  wire                               m_axi_hbm_aclk,
   input  wire                               m_axi_hbm_aresetn,
   input  wire                               s_axi_aclk,
   input  wire                               s_axi_aresetn,
   input  wire                               cam_mem_aclk,
   input  wire                               cam_mem_aresetn,
   // Metadata
   input  wire  [USER_META_DATA_WIDTH-1:0]   user_metadata_in,
   input  wire                               user_metadata_in_valid,
   output reg   [USER_META_DATA_WIDTH-1:0]   user_metadata_out,
   output reg                                user_metadata_out_valid,
   // User Externs
   input  logic [USER_EXTERN_IN_WIDTH-1:0]   user_extern_in,
   input  logic [NUM_USER_EXTERNS-1:0]       user_extern_in_valid,
   output logic [USER_EXTERN_OUT_WIDTH-1:0]  user_extern_out,
   output logic [NUM_USER_EXTERNS-1:0]       user_extern_out_valid,
   // AXI Master port                        
   output reg   [TDATA_NUM_BYTES*8-1:0]      m_axis_tdata,
   output reg   [TDATA_NUM_BYTES-1:0]        m_axis_tkeep,
   output reg                                m_axis_tvalid,
   input  wire                               m_axis_tready,
   output  wire  [TUSER_WIDTH-1:0]           m_axis_tuser,
   output  wire  [TID_WIDTH-1:0]             m_axis_tid,
   output  wire  [TDEST_WIDTH-1:0]           m_axis_tdest,
   output reg                                m_axis_tlast,
   
   // AXI Slave port
   input  wire  [TDATA_NUM_BYTES*8-1:0]      s_axis_tdata,
   input  wire  [TDATA_NUM_BYTES-1:0]        s_axis_tkeep,
   input  wire                               s_axis_tvalid,
   input  wire                               s_axis_tlast,
   input  wire  [TUSER_WIDTH-1:0]            s_axis_tuser,
   input  wire  [TID_WIDTH-1:0]              s_axis_tid,
   input  wire  [TDEST_WIDTH-1:0]            s_axis_tdest,
   output reg                                s_axis_tready,
   // AXI4-full 00 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm00_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm00_awaddr,
   output logic [3:0]                        m_axi_hbm00_awlen,
   output logic [2:0]                        m_axi_hbm00_awsize,
   output logic [1:0]                        m_axi_hbm00_awburst,
   output logic [1:0]                        m_axi_hbm00_awlock,
   output logic [3:0]                        m_axi_hbm00_awcache,
   output logic [2:0]                        m_axi_hbm00_awprot,
   output logic [3:0]                        m_axi_hbm00_awqos,
   output logic [3:0]                        m_axi_hbm00_awregion,
   output logic                              m_axi_hbm00_awvalid,
   input  logic                              m_axi_hbm00_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm00_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm00_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm00_wstrb,
   output logic                              m_axi_hbm00_wlast,
   output logic                              m_axi_hbm00_wvalid,
   input  logic                              m_axi_hbm00_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm00_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm00_bresp,
   input  logic                              m_axi_hbm00_bvalid,
   output logic                              m_axi_hbm00_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm00_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm00_araddr,
   output logic [3:0]                        m_axi_hbm00_arlen,
   output logic [2:0]                        m_axi_hbm00_arsize,
   output logic [1:0]                        m_axi_hbm00_arburst,
   output logic [1:0]                        m_axi_hbm00_arlock,
   output logic [3:0]                        m_axi_hbm00_arcache,
   output logic [2:0]                        m_axi_hbm00_arprot,
   output logic [3:0]                        m_axi_hbm00_arqos,
   output logic [3:0]                        m_axi_hbm00_arregion,
   output logic                              m_axi_hbm00_arvalid,
   input  logic                              m_axi_hbm00_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm00_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm00_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm00_rresp,
   input  logic                              m_axi_hbm00_rlast,
   input  logic                              m_axi_hbm00_rvalid,
   output logic                              m_axi_hbm00_rready,
   // AXI4-full 01 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm01_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm01_awaddr,
   output logic [3:0]                        m_axi_hbm01_awlen,
   output logic [2:0]                        m_axi_hbm01_awsize,
   output logic [1:0]                        m_axi_hbm01_awburst,
   output logic [1:0]                        m_axi_hbm01_awlock,
   output logic [3:0]                        m_axi_hbm01_awcache,
   output logic [2:0]                        m_axi_hbm01_awprot,
   output logic [3:0]                        m_axi_hbm01_awqos,
   output logic [3:0]                        m_axi_hbm01_awregion,
   output logic                              m_axi_hbm01_awvalid,
   input  logic                              m_axi_hbm01_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm01_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm01_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm01_wstrb,
   output logic                              m_axi_hbm01_wlast,
   output logic                              m_axi_hbm01_wvalid,
   input  logic                              m_axi_hbm01_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm01_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm01_bresp,
   input  logic                              m_axi_hbm01_bvalid,
   output logic                              m_axi_hbm01_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm01_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm01_araddr,
   output logic [3:0]                        m_axi_hbm01_arlen,
   output logic [2:0]                        m_axi_hbm01_arsize,
   output logic [1:0]                        m_axi_hbm01_arburst,
   output logic [1:0]                        m_axi_hbm01_arlock,
   output logic [3:0]                        m_axi_hbm01_arcache,
   output logic [2:0]                        m_axi_hbm01_arprot,
   output logic [3:0]                        m_axi_hbm01_arqos,
   output logic [3:0]                        m_axi_hbm01_arregion,
   output logic                              m_axi_hbm01_arvalid,
   input  logic                              m_axi_hbm01_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm01_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm01_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm01_rresp,
   input  logic                              m_axi_hbm01_rlast,
   input  logic                              m_axi_hbm01_rvalid,
   output logic                              m_axi_hbm01_rready,
   // AXI4-full 02 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm02_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm02_awaddr,
   output logic [3:0]                        m_axi_hbm02_awlen,
   output logic [2:0]                        m_axi_hbm02_awsize,
   output logic [1:0]                        m_axi_hbm02_awburst,
   output logic [1:0]                        m_axi_hbm02_awlock,
   output logic [3:0]                        m_axi_hbm02_awcache,
   output logic [2:0]                        m_axi_hbm02_awprot,
   output logic [3:0]                        m_axi_hbm02_awqos,
   output logic [3:0]                        m_axi_hbm02_awregion,
   output logic                              m_axi_hbm02_awvalid,
   input  logic                              m_axi_hbm02_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm02_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm02_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm02_wstrb,
   output logic                              m_axi_hbm02_wlast,
   output logic                              m_axi_hbm02_wvalid,
   input  logic                              m_axi_hbm02_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm02_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm02_bresp,
   input  logic                              m_axi_hbm02_bvalid,
   output logic                              m_axi_hbm02_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm02_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm02_araddr,
   output logic [3:0]                        m_axi_hbm02_arlen,
   output logic [2:0]                        m_axi_hbm02_arsize,
   output logic [1:0]                        m_axi_hbm02_arburst,
   output logic [1:0]                        m_axi_hbm02_arlock,
   output logic [3:0]                        m_axi_hbm02_arcache,
   output logic [2:0]                        m_axi_hbm02_arprot,
   output logic [3:0]                        m_axi_hbm02_arqos,
   output logic [3:0]                        m_axi_hbm02_arregion,
   output logic                              m_axi_hbm02_arvalid,
   input  logic                              m_axi_hbm02_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm02_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm02_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm02_rresp,
   input  logic                              m_axi_hbm02_rlast,
   input  logic                              m_axi_hbm02_rvalid,
   output logic                              m_axi_hbm02_rready,
   // AXI4-full 03 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm03_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm03_awaddr,
   output logic [3:0]                        m_axi_hbm03_awlen,
   output logic [2:0]                        m_axi_hbm03_awsize,
   output logic [1:0]                        m_axi_hbm03_awburst,
   output logic [1:0]                        m_axi_hbm03_awlock,
   output logic [3:0]                        m_axi_hbm03_awcache,
   output logic [2:0]                        m_axi_hbm03_awprot,
   output logic [3:0]                        m_axi_hbm03_awqos,
   output logic [3:0]                        m_axi_hbm03_awregion,
   output logic                              m_axi_hbm03_awvalid,
   input  logic                              m_axi_hbm03_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm03_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm03_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm03_wstrb,
   output logic                              m_axi_hbm03_wlast,
   output logic                              m_axi_hbm03_wvalid,
   input  logic                              m_axi_hbm03_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm03_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm03_bresp,
   input  logic                              m_axi_hbm03_bvalid,
   output logic                              m_axi_hbm03_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm03_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm03_araddr,
   output logic [3:0]                        m_axi_hbm03_arlen,
   output logic [2:0]                        m_axi_hbm03_arsize,
   output logic [1:0]                        m_axi_hbm03_arburst,
   output logic [1:0]                        m_axi_hbm03_arlock,
   output logic [3:0]                        m_axi_hbm03_arcache,
   output logic [2:0]                        m_axi_hbm03_arprot,
   output logic [3:0]                        m_axi_hbm03_arqos,
   output logic [3:0]                        m_axi_hbm03_arregion,
   output logic                              m_axi_hbm03_arvalid,
   input  logic                              m_axi_hbm03_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm03_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm03_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm03_rresp,
   input  logic                              m_axi_hbm03_rlast,
   input  logic                              m_axi_hbm03_rvalid,
   output logic                              m_axi_hbm03_rready,
   // AXI4-full 04 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm04_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm04_awaddr,
   output logic [3:0]                        m_axi_hbm04_awlen,
   output logic [2:0]                        m_axi_hbm04_awsize,
   output logic [1:0]                        m_axi_hbm04_awburst,
   output logic [1:0]                        m_axi_hbm04_awlock,
   output logic [3:0]                        m_axi_hbm04_awcache,
   output logic [2:0]                        m_axi_hbm04_awprot,
   output logic [3:0]                        m_axi_hbm04_awqos,
   output logic [3:0]                        m_axi_hbm04_awregion,
   output logic                              m_axi_hbm04_awvalid,
   input  logic                              m_axi_hbm04_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm04_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm04_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm04_wstrb,
   output logic                              m_axi_hbm04_wlast,
   output logic                              m_axi_hbm04_wvalid,
   input  logic                              m_axi_hbm04_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm04_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm04_bresp,
   input  logic                              m_axi_hbm04_bvalid,
   output logic                              m_axi_hbm04_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm04_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm04_araddr,
   output logic [3:0]                        m_axi_hbm04_arlen,
   output logic [2:0]                        m_axi_hbm04_arsize,
   output logic [1:0]                        m_axi_hbm04_arburst,
   output logic [1:0]                        m_axi_hbm04_arlock,
   output logic [3:0]                        m_axi_hbm04_arcache,
   output logic [2:0]                        m_axi_hbm04_arprot,
   output logic [3:0]                        m_axi_hbm04_arqos,
   output logic [3:0]                        m_axi_hbm04_arregion,
   output logic                              m_axi_hbm04_arvalid,
   input  logic                              m_axi_hbm04_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm04_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm04_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm04_rresp,
   input  logic                              m_axi_hbm04_rlast,
   input  logic                              m_axi_hbm04_rvalid,
   output logic                              m_axi_hbm04_rready,
   // AXI4-full 05 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm05_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm05_awaddr,
   output logic [3:0]                        m_axi_hbm05_awlen,
   output logic [2:0]                        m_axi_hbm05_awsize,
   output logic [1:0]                        m_axi_hbm05_awburst,
   output logic [1:0]                        m_axi_hbm05_awlock,
   output logic [3:0]                        m_axi_hbm05_awcache,
   output logic [2:0]                        m_axi_hbm05_awprot,
   output logic [3:0]                        m_axi_hbm05_awqos,
   output logic [3:0]                        m_axi_hbm05_awregion,
   output logic                              m_axi_hbm05_awvalid,
   input  logic                              m_axi_hbm05_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm05_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm05_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm05_wstrb,
   output logic                              m_axi_hbm05_wlast,
   output logic                              m_axi_hbm05_wvalid,
   input  logic                              m_axi_hbm05_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm05_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm05_bresp,
   input  logic                              m_axi_hbm05_bvalid,
   output logic                              m_axi_hbm05_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm05_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm05_araddr,
   output logic [3:0]                        m_axi_hbm05_arlen,
   output logic [2:0]                        m_axi_hbm05_arsize,
   output logic [1:0]                        m_axi_hbm05_arburst,
   output logic [1:0]                        m_axi_hbm05_arlock,
   output logic [3:0]                        m_axi_hbm05_arcache,
   output logic [2:0]                        m_axi_hbm05_arprot,
   output logic [3:0]                        m_axi_hbm05_arqos,
   output logic [3:0]                        m_axi_hbm05_arregion,
   output logic                              m_axi_hbm05_arvalid,
   input  logic                              m_axi_hbm05_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm05_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm05_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm05_rresp,
   input  logic                              m_axi_hbm05_rlast,
   input  logic                              m_axi_hbm05_rvalid,
   output logic                              m_axi_hbm05_rready,
   // AXI4-full 06 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm06_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm06_awaddr,
   output logic [3:0]                        m_axi_hbm06_awlen,
   output logic [2:0]                        m_axi_hbm06_awsize,
   output logic [1:0]                        m_axi_hbm06_awburst,
   output logic [1:0]                        m_axi_hbm06_awlock,
   output logic [3:0]                        m_axi_hbm06_awcache,
   output logic [2:0]                        m_axi_hbm06_awprot,
   output logic [3:0]                        m_axi_hbm06_awqos,
   output logic [3:0]                        m_axi_hbm06_awregion,
   output logic                              m_axi_hbm06_awvalid,
   input  logic                              m_axi_hbm06_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm06_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm06_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm06_wstrb,
   output logic                              m_axi_hbm06_wlast,
   output logic                              m_axi_hbm06_wvalid,
   input  logic                              m_axi_hbm06_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm06_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm06_bresp,
   input  logic                              m_axi_hbm06_bvalid,
   output logic                              m_axi_hbm06_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm06_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm06_araddr,
   output logic [3:0]                        m_axi_hbm06_arlen,
   output logic [2:0]                        m_axi_hbm06_arsize,
   output logic [1:0]                        m_axi_hbm06_arburst,
   output logic [1:0]                        m_axi_hbm06_arlock,
   output logic [3:0]                        m_axi_hbm06_arcache,
   output logic [2:0]                        m_axi_hbm06_arprot,
   output logic [3:0]                        m_axi_hbm06_arqos,
   output logic [3:0]                        m_axi_hbm06_arregion,
   output logic                              m_axi_hbm06_arvalid,
   input  logic                              m_axi_hbm06_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm06_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm06_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm06_rresp,
   input  logic                              m_axi_hbm06_rlast,
   input  logic                              m_axi_hbm06_rvalid,
   output logic                              m_axi_hbm06_rready,
   // AXI4-full 07 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm07_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm07_awaddr,
   output logic [3:0]                        m_axi_hbm07_awlen,
   output logic [2:0]                        m_axi_hbm07_awsize,
   output logic [1:0]                        m_axi_hbm07_awburst,
   output logic [1:0]                        m_axi_hbm07_awlock,
   output logic [3:0]                        m_axi_hbm07_awcache,
   output logic [2:0]                        m_axi_hbm07_awprot,
   output logic [3:0]                        m_axi_hbm07_awqos,
   output logic [3:0]                        m_axi_hbm07_awregion,
   output logic                              m_axi_hbm07_awvalid,
   input  logic                              m_axi_hbm07_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm07_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm07_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm07_wstrb,
   output logic                              m_axi_hbm07_wlast,
   output logic                              m_axi_hbm07_wvalid,
   input  logic                              m_axi_hbm07_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm07_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm07_bresp,
   input  logic                              m_axi_hbm07_bvalid,
   output logic                              m_axi_hbm07_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm07_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm07_araddr,
   output logic [3:0]                        m_axi_hbm07_arlen,
   output logic [2:0]                        m_axi_hbm07_arsize,
   output logic [1:0]                        m_axi_hbm07_arburst,
   output logic [1:0]                        m_axi_hbm07_arlock,
   output logic [3:0]                        m_axi_hbm07_arcache,
   output logic [2:0]                        m_axi_hbm07_arprot,
   output logic [3:0]                        m_axi_hbm07_arqos,
   output logic [3:0]                        m_axi_hbm07_arregion,
   output logic                              m_axi_hbm07_arvalid,
   input  logic                              m_axi_hbm07_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm07_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm07_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm07_rresp,
   input  logic                              m_axi_hbm07_rlast,
   input  logic                              m_axi_hbm07_rvalid,
   output logic                              m_axi_hbm07_rready,
   // AXI4-full 08 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm08_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm08_awaddr,
   output logic [3:0]                        m_axi_hbm08_awlen,
   output logic [2:0]                        m_axi_hbm08_awsize,
   output logic [1:0]                        m_axi_hbm08_awburst,
   output logic [1:0]                        m_axi_hbm08_awlock,
   output logic [3:0]                        m_axi_hbm08_awcache,
   output logic [2:0]                        m_axi_hbm08_awprot,
   output logic [3:0]                        m_axi_hbm08_awqos,
   output logic [3:0]                        m_axi_hbm08_awregion,
   output logic                              m_axi_hbm08_awvalid,
   input  logic                              m_axi_hbm08_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm08_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm08_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm08_wstrb,
   output logic                              m_axi_hbm08_wlast,
   output logic                              m_axi_hbm08_wvalid,
   input  logic                              m_axi_hbm08_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm08_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm08_bresp,
   input  logic                              m_axi_hbm08_bvalid,
   output logic                              m_axi_hbm08_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm08_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm08_araddr,
   output logic [3:0]                        m_axi_hbm08_arlen,
   output logic [2:0]                        m_axi_hbm08_arsize,
   output logic [1:0]                        m_axi_hbm08_arburst,
   output logic [1:0]                        m_axi_hbm08_arlock,
   output logic [3:0]                        m_axi_hbm08_arcache,
   output logic [2:0]                        m_axi_hbm08_arprot,
   output logic [3:0]                        m_axi_hbm08_arqos,
   output logic [3:0]                        m_axi_hbm08_arregion,
   output logic                              m_axi_hbm08_arvalid,
   input  logic                              m_axi_hbm08_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm08_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm08_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm08_rresp,
   input  logic                              m_axi_hbm08_rlast,
   input  logic                              m_axi_hbm08_rvalid,
   output logic                              m_axi_hbm08_rready,
   // AXI4-full 09 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm09_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm09_awaddr,
   output logic [3:0]                        m_axi_hbm09_awlen,
   output logic [2:0]                        m_axi_hbm09_awsize,
   output logic [1:0]                        m_axi_hbm09_awburst,
   output logic [1:0]                        m_axi_hbm09_awlock,
   output logic [3:0]                        m_axi_hbm09_awcache,
   output logic [2:0]                        m_axi_hbm09_awprot,
   output logic [3:0]                        m_axi_hbm09_awqos,
   output logic [3:0]                        m_axi_hbm09_awregion,
   output logic                              m_axi_hbm09_awvalid,
   input  logic                              m_axi_hbm09_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm09_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm09_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm09_wstrb,
   output logic                              m_axi_hbm09_wlast,
   output logic                              m_axi_hbm09_wvalid,
   input  logic                              m_axi_hbm09_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm09_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm09_bresp,
   input  logic                              m_axi_hbm09_bvalid,
   output logic                              m_axi_hbm09_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm09_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm09_araddr,
   output logic [3:0]                        m_axi_hbm09_arlen,
   output logic [2:0]                        m_axi_hbm09_arsize,
   output logic [1:0]                        m_axi_hbm09_arburst,
   output logic [1:0]                        m_axi_hbm09_arlock,
   output logic [3:0]                        m_axi_hbm09_arcache,
   output logic [2:0]                        m_axi_hbm09_arprot,
   output logic [3:0]                        m_axi_hbm09_arqos,
   output logic [3:0]                        m_axi_hbm09_arregion,
   output logic                              m_axi_hbm09_arvalid,
   input  logic                              m_axi_hbm09_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm09_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm09_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm09_rresp,
   input  logic                              m_axi_hbm09_rlast,
   input  logic                              m_axi_hbm09_rvalid,
   output logic                              m_axi_hbm09_rready,
   // AXI4-full 10 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm10_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm10_awaddr,
   output logic [3:0]                        m_axi_hbm10_awlen,
   output logic [2:0]                        m_axi_hbm10_awsize,
   output logic [1:0]                        m_axi_hbm10_awburst,
   output logic [1:0]                        m_axi_hbm10_awlock,
   output logic [3:0]                        m_axi_hbm10_awcache,
   output logic [2:0]                        m_axi_hbm10_awprot,
   output logic [3:0]                        m_axi_hbm10_awqos,
   output logic [3:0]                        m_axi_hbm10_awregion,
   output logic                              m_axi_hbm10_awvalid,
   input  logic                              m_axi_hbm10_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm10_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm10_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm10_wstrb,
   output logic                              m_axi_hbm10_wlast,
   output logic                              m_axi_hbm10_wvalid,
   input  logic                              m_axi_hbm10_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm10_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm10_bresp,
   input  logic                              m_axi_hbm10_bvalid,
   output logic                              m_axi_hbm10_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm10_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm10_araddr,
   output logic [3:0]                        m_axi_hbm10_arlen,
   output logic [2:0]                        m_axi_hbm10_arsize,
   output logic [1:0]                        m_axi_hbm10_arburst,
   output logic [1:0]                        m_axi_hbm10_arlock,
   output logic [3:0]                        m_axi_hbm10_arcache,
   output logic [2:0]                        m_axi_hbm10_arprot,
   output logic [3:0]                        m_axi_hbm10_arqos,
   output logic [3:0]                        m_axi_hbm10_arregion,
   output logic                              m_axi_hbm10_arvalid,
   input  logic                              m_axi_hbm10_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm10_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm10_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm10_rresp,
   input  logic                              m_axi_hbm10_rlast,
   input  logic                              m_axi_hbm10_rvalid,
   output logic                              m_axi_hbm10_rready,
   // AXI4-full 11 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm11_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm11_awaddr,
   output logic [3:0]                        m_axi_hbm11_awlen,
   output logic [2:0]                        m_axi_hbm11_awsize,
   output logic [1:0]                        m_axi_hbm11_awburst,
   output logic [1:0]                        m_axi_hbm11_awlock,
   output logic [3:0]                        m_axi_hbm11_awcache,
   output logic [2:0]                        m_axi_hbm11_awprot,
   output logic [3:0]                        m_axi_hbm11_awqos,
   output logic [3:0]                        m_axi_hbm11_awregion,
   output logic                              m_axi_hbm11_awvalid,
   input  logic                              m_axi_hbm11_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm11_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm11_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm11_wstrb,
   output logic                              m_axi_hbm11_wlast,
   output logic                              m_axi_hbm11_wvalid,
   input  logic                              m_axi_hbm11_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm11_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm11_bresp,
   input  logic                              m_axi_hbm11_bvalid,
   output logic                              m_axi_hbm11_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm11_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm11_araddr,
   output logic [3:0]                        m_axi_hbm11_arlen,
   output logic [2:0]                        m_axi_hbm11_arsize,
   output logic [1:0]                        m_axi_hbm11_arburst,
   output logic [1:0]                        m_axi_hbm11_arlock,
   output logic [3:0]                        m_axi_hbm11_arcache,
   output logic [2:0]                        m_axi_hbm11_arprot,
   output logic [3:0]                        m_axi_hbm11_arqos,
   output logic [3:0]                        m_axi_hbm11_arregion,
   output logic                              m_axi_hbm11_arvalid,
   input  logic                              m_axi_hbm11_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm11_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm11_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm11_rresp,
   input  logic                              m_axi_hbm11_rlast,
   input  logic                              m_axi_hbm11_rvalid,
   output logic                              m_axi_hbm11_rready,
   // AXI4-full 12 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm12_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm12_awaddr,
   output logic [3:0]                        m_axi_hbm12_awlen,
   output logic [2:0]                        m_axi_hbm12_awsize,
   output logic [1:0]                        m_axi_hbm12_awburst,
   output logic [1:0]                        m_axi_hbm12_awlock,
   output logic [3:0]                        m_axi_hbm12_awcache,
   output logic [2:0]                        m_axi_hbm12_awprot,
   output logic [3:0]                        m_axi_hbm12_awqos,
   output logic [3:0]                        m_axi_hbm12_awregion,
   output logic                              m_axi_hbm12_awvalid,
   input  logic                              m_axi_hbm12_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm12_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm12_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm12_wstrb,
   output logic                              m_axi_hbm12_wlast,
   output logic                              m_axi_hbm12_wvalid,
   input  logic                              m_axi_hbm12_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm12_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm12_bresp,
   input  logic                              m_axi_hbm12_bvalid,
   output logic                              m_axi_hbm12_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm12_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm12_araddr,
   output logic [3:0]                        m_axi_hbm12_arlen,
   output logic [2:0]                        m_axi_hbm12_arsize,
   output logic [1:0]                        m_axi_hbm12_arburst,
   output logic [1:0]                        m_axi_hbm12_arlock,
   output logic [3:0]                        m_axi_hbm12_arcache,
   output logic [2:0]                        m_axi_hbm12_arprot,
   output logic [3:0]                        m_axi_hbm12_arqos,
   output logic [3:0]                        m_axi_hbm12_arregion,
   output logic                              m_axi_hbm12_arvalid,
   input  logic                              m_axi_hbm12_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm12_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm12_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm12_rresp,
   input  logic                              m_axi_hbm12_rlast,
   input  logic                              m_axi_hbm12_rvalid,
   output logic                              m_axi_hbm12_rready,
   // AXI4-full 13 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm13_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm13_awaddr,
   output logic [3:0]                        m_axi_hbm13_awlen,
   output logic [2:0]                        m_axi_hbm13_awsize,
   output logic [1:0]                        m_axi_hbm13_awburst,
   output logic [1:0]                        m_axi_hbm13_awlock,
   output logic [3:0]                        m_axi_hbm13_awcache,
   output logic [2:0]                        m_axi_hbm13_awprot,
   output logic [3:0]                        m_axi_hbm13_awqos,
   output logic [3:0]                        m_axi_hbm13_awregion,
   output logic                              m_axi_hbm13_awvalid,
   input  logic                              m_axi_hbm13_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm13_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm13_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm13_wstrb,
   output logic                              m_axi_hbm13_wlast,
   output logic                              m_axi_hbm13_wvalid,
   input  logic                              m_axi_hbm13_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm13_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm13_bresp,
   input  logic                              m_axi_hbm13_bvalid,
   output logic                              m_axi_hbm13_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm13_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm13_araddr,
   output logic [3:0]                        m_axi_hbm13_arlen,
   output logic [2:0]                        m_axi_hbm13_arsize,
   output logic [1:0]                        m_axi_hbm13_arburst,
   output logic [1:0]                        m_axi_hbm13_arlock,
   output logic [3:0]                        m_axi_hbm13_arcache,
   output logic [2:0]                        m_axi_hbm13_arprot,
   output logic [3:0]                        m_axi_hbm13_arqos,
   output logic [3:0]                        m_axi_hbm13_arregion,
   output logic                              m_axi_hbm13_arvalid,
   input  logic                              m_axi_hbm13_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm13_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm13_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm13_rresp,
   input  logic                              m_axi_hbm13_rlast,
   input  logic                              m_axi_hbm13_rvalid,
   output logic                              m_axi_hbm13_rready,
   // AXI4-full 14 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm14_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm14_awaddr,
   output logic [3:0]                        m_axi_hbm14_awlen,
   output logic [2:0]                        m_axi_hbm14_awsize,
   output logic [1:0]                        m_axi_hbm14_awburst,
   output logic [1:0]                        m_axi_hbm14_awlock,
   output logic [3:0]                        m_axi_hbm14_awcache,
   output logic [2:0]                        m_axi_hbm14_awprot,
   output logic [3:0]                        m_axi_hbm14_awqos,
   output logic [3:0]                        m_axi_hbm14_awregion,
   output logic                              m_axi_hbm14_awvalid,
   input  logic                              m_axi_hbm14_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm14_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm14_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm14_wstrb,
   output logic                              m_axi_hbm14_wlast,
   output logic                              m_axi_hbm14_wvalid,
   input  logic                              m_axi_hbm14_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm14_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm14_bresp,
   input  logic                              m_axi_hbm14_bvalid,
   output logic                              m_axi_hbm14_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm14_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm14_araddr,
   output logic [3:0]                        m_axi_hbm14_arlen,
   output logic [2:0]                        m_axi_hbm14_arsize,
   output logic [1:0]                        m_axi_hbm14_arburst,
   output logic [1:0]                        m_axi_hbm14_arlock,
   output logic [3:0]                        m_axi_hbm14_arcache,
   output logic [2:0]                        m_axi_hbm14_arprot,
   output logic [3:0]                        m_axi_hbm14_arqos,
   output logic [3:0]                        m_axi_hbm14_arregion,
   output logic                              m_axi_hbm14_arvalid,
   input  logic                              m_axi_hbm14_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm14_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm14_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm14_rresp,
   input  logic                              m_axi_hbm14_rlast,
   input  logic                              m_axi_hbm14_rvalid,
   output logic                              m_axi_hbm14_rready,
   // AXI4-full 15 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm15_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm15_awaddr,
   output logic [3:0]                        m_axi_hbm15_awlen,
   output logic [2:0]                        m_axi_hbm15_awsize,
   output logic [1:0]                        m_axi_hbm15_awburst,
   output logic [1:0]                        m_axi_hbm15_awlock,
   output logic [3:0]                        m_axi_hbm15_awcache,
   output logic [2:0]                        m_axi_hbm15_awprot,
   output logic [3:0]                        m_axi_hbm15_awqos,
   output logic [3:0]                        m_axi_hbm15_awregion,
   output logic                              m_axi_hbm15_awvalid,
   input  logic                              m_axi_hbm15_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm15_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm15_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm15_wstrb,
   output logic                              m_axi_hbm15_wlast,
   output logic                              m_axi_hbm15_wvalid,
   input  logic                              m_axi_hbm15_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm15_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm15_bresp,
   input  logic                              m_axi_hbm15_bvalid,
   output logic                              m_axi_hbm15_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm15_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm15_araddr,
   output logic [3:0]                        m_axi_hbm15_arlen,
   output logic [2:0]                        m_axi_hbm15_arsize,
   output logic [1:0]                        m_axi_hbm15_arburst,
   output logic [1:0]                        m_axi_hbm15_arlock,
   output logic [3:0]                        m_axi_hbm15_arcache,
   output logic [2:0]                        m_axi_hbm15_arprot,
   output logic [3:0]                        m_axi_hbm15_arqos,
   output logic [3:0]                        m_axi_hbm15_arregion,
   output logic                              m_axi_hbm15_arvalid,
   input  logic                              m_axi_hbm15_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm15_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm15_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm15_rresp,
   input  logic                              m_axi_hbm15_rlast,
   input  logic                              m_axi_hbm15_rvalid,
   output logic                              m_axi_hbm15_rready,
   // AXI4-full 16 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm16_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm16_awaddr,
   output logic [3:0]                        m_axi_hbm16_awlen,
   output logic [2:0]                        m_axi_hbm16_awsize,
   output logic [1:0]                        m_axi_hbm16_awburst,
   output logic [1:0]                        m_axi_hbm16_awlock,
   output logic [3:0]                        m_axi_hbm16_awcache,
   output logic [2:0]                        m_axi_hbm16_awprot,
   output logic [3:0]                        m_axi_hbm16_awqos,
   output logic [3:0]                        m_axi_hbm16_awregion,
   output logic                              m_axi_hbm16_awvalid,
   input  logic                              m_axi_hbm16_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm16_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm16_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm16_wstrb,
   output logic                              m_axi_hbm16_wlast,
   output logic                              m_axi_hbm16_wvalid,
   input  logic                              m_axi_hbm16_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm16_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm16_bresp,
   input  logic                              m_axi_hbm16_bvalid,
   output logic                              m_axi_hbm16_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm16_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm16_araddr,
   output logic [3:0]                        m_axi_hbm16_arlen,
   output logic [2:0]                        m_axi_hbm16_arsize,
   output logic [1:0]                        m_axi_hbm16_arburst,
   output logic [1:0]                        m_axi_hbm16_arlock,
   output logic [3:0]                        m_axi_hbm16_arcache,
   output logic [2:0]                        m_axi_hbm16_arprot,
   output logic [3:0]                        m_axi_hbm16_arqos,
   output logic [3:0]                        m_axi_hbm16_arregion,
   output logic                              m_axi_hbm16_arvalid,
   input  logic                              m_axi_hbm16_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm16_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm16_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm16_rresp,
   input  logic                              m_axi_hbm16_rlast,
   input  logic                              m_axi_hbm16_rvalid,
   output logic                              m_axi_hbm16_rready,
   // AXI4-full 17 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm17_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm17_awaddr,
   output logic [3:0]                        m_axi_hbm17_awlen,
   output logic [2:0]                        m_axi_hbm17_awsize,
   output logic [1:0]                        m_axi_hbm17_awburst,
   output logic [1:0]                        m_axi_hbm17_awlock,
   output logic [3:0]                        m_axi_hbm17_awcache,
   output logic [2:0]                        m_axi_hbm17_awprot,
   output logic [3:0]                        m_axi_hbm17_awqos,
   output logic [3:0]                        m_axi_hbm17_awregion,
   output logic                              m_axi_hbm17_awvalid,
   input  logic                              m_axi_hbm17_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm17_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm17_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm17_wstrb,
   output logic                              m_axi_hbm17_wlast,
   output logic                              m_axi_hbm17_wvalid,
   input  logic                              m_axi_hbm17_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm17_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm17_bresp,
   input  logic                              m_axi_hbm17_bvalid,
   output logic                              m_axi_hbm17_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm17_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm17_araddr,
   output logic [3:0]                        m_axi_hbm17_arlen,
   output logic [2:0]                        m_axi_hbm17_arsize,
   output logic [1:0]                        m_axi_hbm17_arburst,
   output logic [1:0]                        m_axi_hbm17_arlock,
   output logic [3:0]                        m_axi_hbm17_arcache,
   output logic [2:0]                        m_axi_hbm17_arprot,
   output logic [3:0]                        m_axi_hbm17_arqos,
   output logic [3:0]                        m_axi_hbm17_arregion,
   output logic                              m_axi_hbm17_arvalid,
   input  logic                              m_axi_hbm17_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm17_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm17_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm17_rresp,
   input  logic                              m_axi_hbm17_rlast,
   input  logic                              m_axi_hbm17_rvalid,
   output logic                              m_axi_hbm17_rready,
   // AXI4-full 18 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm18_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm18_awaddr,
   output logic [3:0]                        m_axi_hbm18_awlen,
   output logic [2:0]                        m_axi_hbm18_awsize,
   output logic [1:0]                        m_axi_hbm18_awburst,
   output logic [1:0]                        m_axi_hbm18_awlock,
   output logic [3:0]                        m_axi_hbm18_awcache,
   output logic [2:0]                        m_axi_hbm18_awprot,
   output logic [3:0]                        m_axi_hbm18_awqos,
   output logic [3:0]                        m_axi_hbm18_awregion,
   output logic                              m_axi_hbm18_awvalid,
   input  logic                              m_axi_hbm18_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm18_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm18_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm18_wstrb,
   output logic                              m_axi_hbm18_wlast,
   output logic                              m_axi_hbm18_wvalid,
   input  logic                              m_axi_hbm18_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm18_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm18_bresp,
   input  logic                              m_axi_hbm18_bvalid,
   output logic                              m_axi_hbm18_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm18_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm18_araddr,
   output logic [3:0]                        m_axi_hbm18_arlen,
   output logic [2:0]                        m_axi_hbm18_arsize,
   output logic [1:0]                        m_axi_hbm18_arburst,
   output logic [1:0]                        m_axi_hbm18_arlock,
   output logic [3:0]                        m_axi_hbm18_arcache,
   output logic [2:0]                        m_axi_hbm18_arprot,
   output logic [3:0]                        m_axi_hbm18_arqos,
   output logic [3:0]                        m_axi_hbm18_arregion,
   output logic                              m_axi_hbm18_arvalid,
   input  logic                              m_axi_hbm18_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm18_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm18_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm18_rresp,
   input  logic                              m_axi_hbm18_rlast,
   input  logic                              m_axi_hbm18_rvalid,
   output logic                              m_axi_hbm18_rready,
   // AXI4-full 19 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm19_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm19_awaddr,
   output logic [3:0]                        m_axi_hbm19_awlen,
   output logic [2:0]                        m_axi_hbm19_awsize,
   output logic [1:0]                        m_axi_hbm19_awburst,
   output logic [1:0]                        m_axi_hbm19_awlock,
   output logic [3:0]                        m_axi_hbm19_awcache,
   output logic [2:0]                        m_axi_hbm19_awprot,
   output logic [3:0]                        m_axi_hbm19_awqos,
   output logic [3:0]                        m_axi_hbm19_awregion,
   output logic                              m_axi_hbm19_awvalid,
   input  logic                              m_axi_hbm19_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm19_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm19_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm19_wstrb,
   output logic                              m_axi_hbm19_wlast,
   output logic                              m_axi_hbm19_wvalid,
   input  logic                              m_axi_hbm19_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm19_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm19_bresp,
   input  logic                              m_axi_hbm19_bvalid,
   output logic                              m_axi_hbm19_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm19_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm19_araddr,
   output logic [3:0]                        m_axi_hbm19_arlen,
   output logic [2:0]                        m_axi_hbm19_arsize,
   output logic [1:0]                        m_axi_hbm19_arburst,
   output logic [1:0]                        m_axi_hbm19_arlock,
   output logic [3:0]                        m_axi_hbm19_arcache,
   output logic [2:0]                        m_axi_hbm19_arprot,
   output logic [3:0]                        m_axi_hbm19_arqos,
   output logic [3:0]                        m_axi_hbm19_arregion,
   output logic                              m_axi_hbm19_arvalid,
   input  logic                              m_axi_hbm19_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm19_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm19_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm19_rresp,
   input  logic                              m_axi_hbm19_rlast,
   input  logic                              m_axi_hbm19_rvalid,
   output logic                              m_axi_hbm19_rready,
   // AXI4-full 20 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm20_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm20_awaddr,
   output logic [3:0]                        m_axi_hbm20_awlen,
   output logic [2:0]                        m_axi_hbm20_awsize,
   output logic [1:0]                        m_axi_hbm20_awburst,
   output logic [1:0]                        m_axi_hbm20_awlock,
   output logic [3:0]                        m_axi_hbm20_awcache,
   output logic [2:0]                        m_axi_hbm20_awprot,
   output logic [3:0]                        m_axi_hbm20_awqos,
   output logic [3:0]                        m_axi_hbm20_awregion,
   output logic                              m_axi_hbm20_awvalid,
   input  logic                              m_axi_hbm20_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm20_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm20_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm20_wstrb,
   output logic                              m_axi_hbm20_wlast,
   output logic                              m_axi_hbm20_wvalid,
   input  logic                              m_axi_hbm20_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm20_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm20_bresp,
   input  logic                              m_axi_hbm20_bvalid,
   output logic                              m_axi_hbm20_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm20_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm20_araddr,
   output logic [3:0]                        m_axi_hbm20_arlen,
   output logic [2:0]                        m_axi_hbm20_arsize,
   output logic [1:0]                        m_axi_hbm20_arburst,
   output logic [1:0]                        m_axi_hbm20_arlock,
   output logic [3:0]                        m_axi_hbm20_arcache,
   output logic [2:0]                        m_axi_hbm20_arprot,
   output logic [3:0]                        m_axi_hbm20_arqos,
   output logic [3:0]                        m_axi_hbm20_arregion,
   output logic                              m_axi_hbm20_arvalid,
   input  logic                              m_axi_hbm20_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm20_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm20_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm20_rresp,
   input  logic                              m_axi_hbm20_rlast,
   input  logic                              m_axi_hbm20_rvalid,
   output logic                              m_axi_hbm20_rready,
   // AXI4-full 21 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm21_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm21_awaddr,
   output logic [3:0]                        m_axi_hbm21_awlen,
   output logic [2:0]                        m_axi_hbm21_awsize,
   output logic [1:0]                        m_axi_hbm21_awburst,
   output logic [1:0]                        m_axi_hbm21_awlock,
   output logic [3:0]                        m_axi_hbm21_awcache,
   output logic [2:0]                        m_axi_hbm21_awprot,
   output logic [3:0]                        m_axi_hbm21_awqos,
   output logic [3:0]                        m_axi_hbm21_awregion,
   output logic                              m_axi_hbm21_awvalid,
   input  logic                              m_axi_hbm21_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm21_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm21_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm21_wstrb,
   output logic                              m_axi_hbm21_wlast,
   output logic                              m_axi_hbm21_wvalid,
   input  logic                              m_axi_hbm21_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm21_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm21_bresp,
   input  logic                              m_axi_hbm21_bvalid,
   output logic                              m_axi_hbm21_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm21_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm21_araddr,
   output logic [3:0]                        m_axi_hbm21_arlen,
   output logic [2:0]                        m_axi_hbm21_arsize,
   output logic [1:0]                        m_axi_hbm21_arburst,
   output logic [1:0]                        m_axi_hbm21_arlock,
   output logic [3:0]                        m_axi_hbm21_arcache,
   output logic [2:0]                        m_axi_hbm21_arprot,
   output logic [3:0]                        m_axi_hbm21_arqos,
   output logic [3:0]                        m_axi_hbm21_arregion,
   output logic                              m_axi_hbm21_arvalid,
   input  logic                              m_axi_hbm21_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm21_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm21_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm21_rresp,
   input  logic                              m_axi_hbm21_rlast,
   input  logic                              m_axi_hbm21_rvalid,
   output logic                              m_axi_hbm21_rready,
   // AXI4-full 22 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm22_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm22_awaddr,
   output logic [3:0]                        m_axi_hbm22_awlen,
   output logic [2:0]                        m_axi_hbm22_awsize,
   output logic [1:0]                        m_axi_hbm22_awburst,
   output logic [1:0]                        m_axi_hbm22_awlock,
   output logic [3:0]                        m_axi_hbm22_awcache,
   output logic [2:0]                        m_axi_hbm22_awprot,
   output logic [3:0]                        m_axi_hbm22_awqos,
   output logic [3:0]                        m_axi_hbm22_awregion,
   output logic                              m_axi_hbm22_awvalid,
   input  logic                              m_axi_hbm22_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm22_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm22_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm22_wstrb,
   output logic                              m_axi_hbm22_wlast,
   output logic                              m_axi_hbm22_wvalid,
   input  logic                              m_axi_hbm22_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm22_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm22_bresp,
   input  logic                              m_axi_hbm22_bvalid,
   output logic                              m_axi_hbm22_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm22_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm22_araddr,
   output logic [3:0]                        m_axi_hbm22_arlen,
   output logic [2:0]                        m_axi_hbm22_arsize,
   output logic [1:0]                        m_axi_hbm22_arburst,
   output logic [1:0]                        m_axi_hbm22_arlock,
   output logic [3:0]                        m_axi_hbm22_arcache,
   output logic [2:0]                        m_axi_hbm22_arprot,
   output logic [3:0]                        m_axi_hbm22_arqos,
   output logic [3:0]                        m_axi_hbm22_arregion,
   output logic                              m_axi_hbm22_arvalid,
   input  logic                              m_axi_hbm22_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm22_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm22_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm22_rresp,
   input  logic                              m_axi_hbm22_rlast,
   input  logic                              m_axi_hbm22_rvalid,
   output logic                              m_axi_hbm22_rready,
   // AXI4-full 23 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm23_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm23_awaddr,
   output logic [3:0]                        m_axi_hbm23_awlen,
   output logic [2:0]                        m_axi_hbm23_awsize,
   output logic [1:0]                        m_axi_hbm23_awburst,
   output logic [1:0]                        m_axi_hbm23_awlock,
   output logic [3:0]                        m_axi_hbm23_awcache,
   output logic [2:0]                        m_axi_hbm23_awprot,
   output logic [3:0]                        m_axi_hbm23_awqos,
   output logic [3:0]                        m_axi_hbm23_awregion,
   output logic                              m_axi_hbm23_awvalid,
   input  logic                              m_axi_hbm23_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm23_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm23_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm23_wstrb,
   output logic                              m_axi_hbm23_wlast,
   output logic                              m_axi_hbm23_wvalid,
   input  logic                              m_axi_hbm23_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm23_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm23_bresp,
   input  logic                              m_axi_hbm23_bvalid,
   output logic                              m_axi_hbm23_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm23_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm23_araddr,
   output logic [3:0]                        m_axi_hbm23_arlen,
   output logic [2:0]                        m_axi_hbm23_arsize,
   output logic [1:0]                        m_axi_hbm23_arburst,
   output logic [1:0]                        m_axi_hbm23_arlock,
   output logic [3:0]                        m_axi_hbm23_arcache,
   output logic [2:0]                        m_axi_hbm23_arprot,
   output logic [3:0]                        m_axi_hbm23_arqos,
   output logic [3:0]                        m_axi_hbm23_arregion,
   output logic                              m_axi_hbm23_arvalid,
   input  logic                              m_axi_hbm23_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm23_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm23_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm23_rresp,
   input  logic                              m_axi_hbm23_rlast,
   input  logic                              m_axi_hbm23_rvalid,
   output logic                              m_axi_hbm23_rready,
   // AXI4-full 24 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm24_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm24_awaddr,
   output logic [3:0]                        m_axi_hbm24_awlen,
   output logic [2:0]                        m_axi_hbm24_awsize,
   output logic [1:0]                        m_axi_hbm24_awburst,
   output logic [1:0]                        m_axi_hbm24_awlock,
   output logic [3:0]                        m_axi_hbm24_awcache,
   output logic [2:0]                        m_axi_hbm24_awprot,
   output logic [3:0]                        m_axi_hbm24_awqos,
   output logic [3:0]                        m_axi_hbm24_awregion,
   output logic                              m_axi_hbm24_awvalid,
   input  logic                              m_axi_hbm24_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm24_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm24_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm24_wstrb,
   output logic                              m_axi_hbm24_wlast,
   output logic                              m_axi_hbm24_wvalid,
   input  logic                              m_axi_hbm24_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm24_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm24_bresp,
   input  logic                              m_axi_hbm24_bvalid,
   output logic                              m_axi_hbm24_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm24_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm24_araddr,
   output logic [3:0]                        m_axi_hbm24_arlen,
   output logic [2:0]                        m_axi_hbm24_arsize,
   output logic [1:0]                        m_axi_hbm24_arburst,
   output logic [1:0]                        m_axi_hbm24_arlock,
   output logic [3:0]                        m_axi_hbm24_arcache,
   output logic [2:0]                        m_axi_hbm24_arprot,
   output logic [3:0]                        m_axi_hbm24_arqos,
   output logic [3:0]                        m_axi_hbm24_arregion,
   output logic                              m_axi_hbm24_arvalid,
   input  logic                              m_axi_hbm24_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm24_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm24_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm24_rresp,
   input  logic                              m_axi_hbm24_rlast,
   input  logic                              m_axi_hbm24_rvalid,
   output logic                              m_axi_hbm24_rready,
   // AXI4-full 25 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm25_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm25_awaddr,
   output logic [3:0]                        m_axi_hbm25_awlen,
   output logic [2:0]                        m_axi_hbm25_awsize,
   output logic [1:0]                        m_axi_hbm25_awburst,
   output logic [1:0]                        m_axi_hbm25_awlock,
   output logic [3:0]                        m_axi_hbm25_awcache,
   output logic [2:0]                        m_axi_hbm25_awprot,
   output logic [3:0]                        m_axi_hbm25_awqos,
   output logic [3:0]                        m_axi_hbm25_awregion,
   output logic                              m_axi_hbm25_awvalid,
   input  logic                              m_axi_hbm25_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm25_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm25_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm25_wstrb,
   output logic                              m_axi_hbm25_wlast,
   output logic                              m_axi_hbm25_wvalid,
   input  logic                              m_axi_hbm25_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm25_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm25_bresp,
   input  logic                              m_axi_hbm25_bvalid,
   output logic                              m_axi_hbm25_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm25_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm25_araddr,
   output logic [3:0]                        m_axi_hbm25_arlen,
   output logic [2:0]                        m_axi_hbm25_arsize,
   output logic [1:0]                        m_axi_hbm25_arburst,
   output logic [1:0]                        m_axi_hbm25_arlock,
   output logic [3:0]                        m_axi_hbm25_arcache,
   output logic [2:0]                        m_axi_hbm25_arprot,
   output logic [3:0]                        m_axi_hbm25_arqos,
   output logic [3:0]                        m_axi_hbm25_arregion,
   output logic                              m_axi_hbm25_arvalid,
   input  logic                              m_axi_hbm25_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm25_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm25_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm25_rresp,
   input  logic                              m_axi_hbm25_rlast,
   input  logic                              m_axi_hbm25_rvalid,
   output logic                              m_axi_hbm25_rready,
   // AXI4-full 26 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm26_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm26_awaddr,
   output logic [3:0]                        m_axi_hbm26_awlen,
   output logic [2:0]                        m_axi_hbm26_awsize,
   output logic [1:0]                        m_axi_hbm26_awburst,
   output logic [1:0]                        m_axi_hbm26_awlock,
   output logic [3:0]                        m_axi_hbm26_awcache,
   output logic [2:0]                        m_axi_hbm26_awprot,
   output logic [3:0]                        m_axi_hbm26_awqos,
   output logic [3:0]                        m_axi_hbm26_awregion,
   output logic                              m_axi_hbm26_awvalid,
   input  logic                              m_axi_hbm26_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm26_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm26_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm26_wstrb,
   output logic                              m_axi_hbm26_wlast,
   output logic                              m_axi_hbm26_wvalid,
   input  logic                              m_axi_hbm26_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm26_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm26_bresp,
   input  logic                              m_axi_hbm26_bvalid,
   output logic                              m_axi_hbm26_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm26_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm26_araddr,
   output logic [3:0]                        m_axi_hbm26_arlen,
   output logic [2:0]                        m_axi_hbm26_arsize,
   output logic [1:0]                        m_axi_hbm26_arburst,
   output logic [1:0]                        m_axi_hbm26_arlock,
   output logic [3:0]                        m_axi_hbm26_arcache,
   output logic [2:0]                        m_axi_hbm26_arprot,
   output logic [3:0]                        m_axi_hbm26_arqos,
   output logic [3:0]                        m_axi_hbm26_arregion,
   output logic                              m_axi_hbm26_arvalid,
   input  logic                              m_axi_hbm26_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm26_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm26_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm26_rresp,
   input  logic                              m_axi_hbm26_rlast,
   input  logic                              m_axi_hbm26_rvalid,
   output logic                              m_axi_hbm26_rready,
   // AXI4-full 27 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm27_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm27_awaddr,
   output logic [3:0]                        m_axi_hbm27_awlen,
   output logic [2:0]                        m_axi_hbm27_awsize,
   output logic [1:0]                        m_axi_hbm27_awburst,
   output logic [1:0]                        m_axi_hbm27_awlock,
   output logic [3:0]                        m_axi_hbm27_awcache,
   output logic [2:0]                        m_axi_hbm27_awprot,
   output logic [3:0]                        m_axi_hbm27_awqos,
   output logic [3:0]                        m_axi_hbm27_awregion,
   output logic                              m_axi_hbm27_awvalid,
   input  logic                              m_axi_hbm27_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm27_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm27_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm27_wstrb,
   output logic                              m_axi_hbm27_wlast,
   output logic                              m_axi_hbm27_wvalid,
   input  logic                              m_axi_hbm27_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm27_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm27_bresp,
   input  logic                              m_axi_hbm27_bvalid,
   output logic                              m_axi_hbm27_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm27_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm27_araddr,
   output logic [3:0]                        m_axi_hbm27_arlen,
   output logic [2:0]                        m_axi_hbm27_arsize,
   output logic [1:0]                        m_axi_hbm27_arburst,
   output logic [1:0]                        m_axi_hbm27_arlock,
   output logic [3:0]                        m_axi_hbm27_arcache,
   output logic [2:0]                        m_axi_hbm27_arprot,
   output logic [3:0]                        m_axi_hbm27_arqos,
   output logic [3:0]                        m_axi_hbm27_arregion,
   output logic                              m_axi_hbm27_arvalid,
   input  logic                              m_axi_hbm27_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm27_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm27_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm27_rresp,
   input  logic                              m_axi_hbm27_rlast,
   input  logic                              m_axi_hbm27_rvalid,
   output logic                              m_axi_hbm27_rready,
   // AXI4-full 28 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm28_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm28_awaddr,
   output logic [3:0]                        m_axi_hbm28_awlen,
   output logic [2:0]                        m_axi_hbm28_awsize,
   output logic [1:0]                        m_axi_hbm28_awburst,
   output logic [1:0]                        m_axi_hbm28_awlock,
   output logic [3:0]                        m_axi_hbm28_awcache,
   output logic [2:0]                        m_axi_hbm28_awprot,
   output logic [3:0]                        m_axi_hbm28_awqos,
   output logic [3:0]                        m_axi_hbm28_awregion,
   output logic                              m_axi_hbm28_awvalid,
   input  logic                              m_axi_hbm28_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm28_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm28_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm28_wstrb,
   output logic                              m_axi_hbm28_wlast,
   output logic                              m_axi_hbm28_wvalid,
   input  logic                              m_axi_hbm28_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm28_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm28_bresp,
   input  logic                              m_axi_hbm28_bvalid,
   output logic                              m_axi_hbm28_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm28_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm28_araddr,
   output logic [3:0]                        m_axi_hbm28_arlen,
   output logic [2:0]                        m_axi_hbm28_arsize,
   output logic [1:0]                        m_axi_hbm28_arburst,
   output logic [1:0]                        m_axi_hbm28_arlock,
   output logic [3:0]                        m_axi_hbm28_arcache,
   output logic [2:0]                        m_axi_hbm28_arprot,
   output logic [3:0]                        m_axi_hbm28_arqos,
   output logic [3:0]                        m_axi_hbm28_arregion,
   output logic                              m_axi_hbm28_arvalid,
   input  logic                              m_axi_hbm28_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm28_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm28_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm28_rresp,
   input  logic                              m_axi_hbm28_rlast,
   input  logic                              m_axi_hbm28_rvalid,
   output logic                              m_axi_hbm28_rready,
   // AXI4-full 29 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm29_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm29_awaddr,
   output logic [3:0]                        m_axi_hbm29_awlen,
   output logic [2:0]                        m_axi_hbm29_awsize,
   output logic [1:0]                        m_axi_hbm29_awburst,
   output logic [1:0]                        m_axi_hbm29_awlock,
   output logic [3:0]                        m_axi_hbm29_awcache,
   output logic [2:0]                        m_axi_hbm29_awprot,
   output logic [3:0]                        m_axi_hbm29_awqos,
   output logic [3:0]                        m_axi_hbm29_awregion,
   output logic                              m_axi_hbm29_awvalid,
   input  logic                              m_axi_hbm29_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm29_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm29_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm29_wstrb,
   output logic                              m_axi_hbm29_wlast,
   output logic                              m_axi_hbm29_wvalid,
   input  logic                              m_axi_hbm29_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm29_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm29_bresp,
   input  logic                              m_axi_hbm29_bvalid,
   output logic                              m_axi_hbm29_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm29_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm29_araddr,
   output logic [3:0]                        m_axi_hbm29_arlen,
   output logic [2:0]                        m_axi_hbm29_arsize,
   output logic [1:0]                        m_axi_hbm29_arburst,
   output logic [1:0]                        m_axi_hbm29_arlock,
   output logic [3:0]                        m_axi_hbm29_arcache,
   output logic [2:0]                        m_axi_hbm29_arprot,
   output logic [3:0]                        m_axi_hbm29_arqos,
   output logic [3:0]                        m_axi_hbm29_arregion,
   output logic                              m_axi_hbm29_arvalid,
   input  logic                              m_axi_hbm29_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm29_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm29_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm29_rresp,
   input  logic                              m_axi_hbm29_rlast,
   input  logic                              m_axi_hbm29_rvalid,
   output logic                              m_axi_hbm29_rready,
   // AXI4-full 30 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm30_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm30_awaddr,
   output logic [3:0]                        m_axi_hbm30_awlen,
   output logic [2:0]                        m_axi_hbm30_awsize,
   output logic [1:0]                        m_axi_hbm30_awburst,
   output logic [1:0]                        m_axi_hbm30_awlock,
   output logic [3:0]                        m_axi_hbm30_awcache,
   output logic [2:0]                        m_axi_hbm30_awprot,
   output logic [3:0]                        m_axi_hbm30_awqos,
   output logic [3:0]                        m_axi_hbm30_awregion,
   output logic                              m_axi_hbm30_awvalid,
   input  logic                              m_axi_hbm30_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm30_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm30_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm30_wstrb,
   output logic                              m_axi_hbm30_wlast,
   output logic                              m_axi_hbm30_wvalid,
   input  logic                              m_axi_hbm30_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm30_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm30_bresp,
   input  logic                              m_axi_hbm30_bvalid,
   output logic                              m_axi_hbm30_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm30_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm30_araddr,
   output logic [3:0]                        m_axi_hbm30_arlen,
   output logic [2:0]                        m_axi_hbm30_arsize,
   output logic [1:0]                        m_axi_hbm30_arburst,
   output logic [1:0]                        m_axi_hbm30_arlock,
   output logic [3:0]                        m_axi_hbm30_arcache,
   output logic [2:0]                        m_axi_hbm30_arprot,
   output logic [3:0]                        m_axi_hbm30_arqos,
   output logic [3:0]                        m_axi_hbm30_arregion,
   output logic                              m_axi_hbm30_arvalid,
   input  logic                              m_axi_hbm30_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm30_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm30_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm30_rresp,
   input  logic                              m_axi_hbm30_rlast,
   input  logic                              m_axi_hbm30_rvalid,
   output logic                              m_axi_hbm30_rready,
   // AXI4-full 31 interface
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm31_awid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm31_awaddr,
   output logic [3:0]                        m_axi_hbm31_awlen,
   output logic [2:0]                        m_axi_hbm31_awsize,
   output logic [1:0]                        m_axi_hbm31_awburst,
   output logic [1:0]                        m_axi_hbm31_awlock,
   output logic [3:0]                        m_axi_hbm31_awcache,
   output logic [2:0]                        m_axi_hbm31_awprot,
   output logic [3:0]                        m_axi_hbm31_awqos,
   output logic [3:0]                        m_axi_hbm31_awregion,
   output logic                              m_axi_hbm31_awvalid,
   input  logic                              m_axi_hbm31_awready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm31_wid,
   output logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm31_wdata,
   output logic [M_AXI_HBM_DATA_WIDTH/8-1:0] m_axi_hbm31_wstrb,
   output logic                              m_axi_hbm31_wlast,
   output logic                              m_axi_hbm31_wvalid,
   input  logic                              m_axi_hbm31_wready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm31_bid,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm31_bresp,
   input  logic                              m_axi_hbm31_bvalid,
   output logic                              m_axi_hbm31_bready,
   output logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm31_arid,
   output logic [M_AXI_HBM_ADDR_WIDTH-1:0]   m_axi_hbm31_araddr,
   output logic [3:0]                        m_axi_hbm31_arlen,
   output logic [2:0]                        m_axi_hbm31_arsize,
   output logic [1:0]                        m_axi_hbm31_arburst,
   output logic [1:0]                        m_axi_hbm31_arlock,
   output logic [3:0]                        m_axi_hbm31_arcache,
   output logic [2:0]                        m_axi_hbm31_arprot,
   output logic [3:0]                        m_axi_hbm31_arqos,
   output logic [3:0]                        m_axi_hbm31_arregion,
   output logic                              m_axi_hbm31_arvalid,
   input  logic                              m_axi_hbm31_arready,
   input  logic [M_AXI_HBM_ID_WIDTH-1:0]     m_axi_hbm31_rid,
   input  logic [M_AXI_HBM_DATA_WIDTH-1:0]   m_axi_hbm31_rdata,
   input  logic [M_AXI_HBM_RESP_WIDTH-1:0]   m_axi_hbm31_rresp,
   input  logic                              m_axi_hbm31_rlast,
   input  logic                              m_axi_hbm31_rvalid,
   output logic                              m_axi_hbm31_rready,
   // AXI4-lite interface                   
   input  wire  [S_AXI_ADDR_WIDTH-1:0]       s_axi_awaddr,
   input  wire                               s_axi_awvalid,
   output reg                                s_axi_awready,
   input  wire  [S_AXI_DATA_WIDTH-1:0]       s_axi_wdata,
   input  wire  [S_AXI_DATA_WIDTH/8-1:0]     s_axi_wstrb,
   input  wire                               s_axi_wvalid,
   output reg                                s_axi_wready,
   output reg   [1:0]                        s_axi_bresp,
   output reg                                s_axi_bvalid,
   input  wire                               s_axi_bready,
   input  wire  [S_AXI_ADDR_WIDTH-1:0]       s_axi_araddr,
   input  wire                               s_axi_arvalid,
   output reg                                s_axi_arready,
   output reg   [S_AXI_DATA_WIDTH-1:0]       s_axi_rdata,
   output reg                                s_axi_rvalid,
   input  wire                               s_axi_rready,
   output reg   [1:0]                        s_axi_rresp,
   // Interrupt request
   output logic irq
);

ipsec_bd_sdnet_0_3_sdnet inst( .* );

endmodule
